name: Structure Data Project

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve \
          -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}"

      - name: Get deployment outputs
        working-directory: ./terraform
        run: |
          echo "API_URL=$(terraform output -raw api_url)" >> $GITHUB_ENV
          echo "COGNITO_REGION=$(terraform output -raw cognito_region)" >> $GITHUB_ENV
          echo "COGNITO_USER_POOL_ID=$(terraform output -raw cognito_user_pool_id)" >> $GITHUB_ENV
          echo "COGNITO_CLIENT_ID=$(terraform output -raw cognito_user_pool_client_id)" >> $GITHUB_ENV

      - name: Inject runtime config into JS
      # These will automatically change placeholders with URLs coming from AWS
        run: |
            cp s3-frontend/index.js s3-frontend/index.tmp.js
            cp s3-frontend/login.js s3-frontend/login.tmp.js

            sed -i "s|__API_URL__|$API_URL|g" s3-frontend/index.tmp.js
            sed -i "s|__COGNITO_REGION__|$COGNITO_REGION|g" s3-frontend/login.tmp.js
            sed -i "s|__COGNITO_USER_POOL_ID__|$COGNITO_USER_POOL_ID|g" s3-frontend/login.tmp.js
            sed -i "s|__COGNITO_CLIENT_ID__|$COGNITO_CLIENT_ID|g" s3-frontend/login.tmp.js

      - name: Upload static frontend files to S3
        run: |
            aws s3 cp s3-frontend/index.html s3://${{ secrets.S3_BUCKET_NAME }}/index.html \
            --content-type text/html
            
            aws s3 cp s3-frontend/login.html s3://${{ secrets.S3_BUCKET_NAME }}/login.html \
            --content-type text/html
            
            aws s3 cp s3-frontend/project-style.css s3://${{ secrets.S3_BUCKET_NAME }}/project-style.css \
            --content-type text/css
            
            aws s3 cp s3-frontend/login-style.css s3://${{ secrets.S3_BUCKET_NAME }}/login-style.css \
            --content-type text/css
            
            aws s3 cp s3-frontend/index.tmp.js s3://${{ secrets.S3_BUCKET_NAME }}/index.js \
            --content-type application/javascript
            
            aws s3 cp s3-frontend/login.tmp.js s3://${{ secrets.S3_BUCKET_NAME }}/login.js \
            --content-type application/javascript

      - name: Zip the Lambda function first
        working-directory: ./lambda-function
        run: zip function.zip structured_dataproject.py

      - name: Update Lambda code
        working-directory: ./lambda-function
        run: |
          aws lambda update-function-code \
            --function-name structured_function \
            --zip-file fileb://function.zip
